= Executive summary

Organisations need assistants that can answer from internal documents while respecting who may use each specialist capability. A conversational interface alone does not establish those boundaries, especially when one assistant calls another. NTG-agent-vnext addresses this problem by extending NashTech's existing .NET agent platform with administrator-configured, document-grounded assistants and caller-aware specialist delegation.

The solution gives each knowledge-enabled agent a dedicated retrieval context. An outer agent can invoke an eligible inner agent as a tool; the inner agent searches its own knowledge and returns an answer. The runtime checks access when exposing the specialist and again when invoking it. Administrators configure the documents, roles and capability bindings that govern this workflow. Provider catalogues and live thinking-compatibility probes support usable model selection, while AG-UI events and declarative surfaces support structured interaction. Skills can supply authored templates populated at runtime, reducing the need for a bespoke frontend component for each supported task variation.

The team's engineering contribution centres on four connected areas: agent-scoped knowledge services, specialist delegation, caller-aware access control and reusable interactive interfaces. Reviewed history across twelve GitHub pull requests substantiates their integration and the supporting provider, lifecycle and installation work. These contributions extend an inherited platform and reused frameworks; they do not constitute a new retrieval algorithm. Per-agent knowledge ownership was retained instead of the planned many-to-many shared knowledge spaces, and the legacy long-term memory/search stack was removed. Delivery and scope changes are assessed against the completion plan rather than treated as uniform completion of its ambitions.

The supplied retrieval trials provide a preliminary quantitative result. Across twelve pilot questions, all four LightRAG modes achieved a reported hit\@5 of 0.917, exceeding the plan's numerical threshold of 0.80 on that set. A warm-cache rerun preserved the hit rates. Graph-based modes had higher relative median retrieval latency without higher aggregate hit\@5 in the cold pilot, making the simpler mode a useful baseline for similar questions. These observations concern retrieval coverage on a small development corpus. They do not establish human-rated answer correctness, end-to-end permission enforcement or performance on representative enterprise workloads.

The practical outcome is a traceable platform extension for configuring document-grounded specialist workflows. Its access mechanisms are supported by implementation evidence; behavioural assurance requires recorded authorised and unauthorised cases, alongside answer assessment and the remaining operational measurements. The report develops this argument through the application needs and market alternatives, explains the design and delivery, then evaluates accomplishments and retrieval findings against the original criteria. The final reflection identifies lessons and priorities for validating the integrated workflow.
