= Executive summary

NTG-agent-vnext extends NashTech's existing .NET agent application to support configurable, document-grounded specialist workflows. The QUOTA team's capstone addresses a practical need: users require access to relevant organisational knowledge and task assistance, while administrators must control which agents, documents, tools and model configurations are available. A conversational interface alone does not resolve these requirements. Permissions must remain effective during delegation, provider settings must correspond to usable requests, and structured tasks need an interface that can preserve inputs and progress.

The solution connects a .NET orchestration backend and administration interface with LightRAG knowledge services and an AG-UI conversational client. Each knowledge-enabled agent has a dedicated retrieval context. An outer agent can invoke an authorised inner agent as a tool; the inner agent queries its own knowledge base and returns an answer. Access is checked when exposing the tool and again when invoking it. Administrators can also manage provider model catalogues, test thinking compatibility through the runtime client-construction path, and bind skills containing instructions and validated interface templates.

The reviewed development history substantiates these contributions across twelve GitHub pull requests and twenty-two feature workstreams. Agents-as-tools reached main on 19 June, AG-UI on 7 July, the core knowledge branch on 17 July and role-based access on 23 July. Subsequent integration delivered VM/gateway work on 20 August, skills on 25 August, provider/model management on 3 September and installation automation on 13 September. The record also identifies cross-support between members, including provider routing, legacy-stack removal and macOS setup. These are integration milestones; operational acceptance is assessed separately.

The supplied retrieval trials provide an initial quantitative result. Across twelve pilot questions, all four LightRAG modes achieved a reported hit\@5 of 0.917, exceeding the completion plan's numerical threshold of 0.80 on that task set. A warm-cache rerun preserved the reported hit rates. The cold pilot nevertheless showed higher relative median retrieval latency for graph-based modes without higher aggregate hit\@5, making the simpler mode a useful baseline for similar questions. A question missed by every mode supplies a concrete diagnostic case. The findings support retrieval coverage and repeated-query consistency under the supplied configuration; they do not establish human-rated answer correctness or performance on a representative enterprise workload.

Delivery was selective rather than uniform across the original ambitions. The implementation retains per-agent knowledge ownership instead of the planned many-to-many shared knowledge spaces, and the earlier long-term memory/search stack was removed. Access control and skills were integrated before the 26 August Phase 2 milestone; the expanded provider workflow merged eight days afterwards. Human answer assessment and several latency, cost and reliability targets remain to be verified. The practical contribution is therefore an integrated and traceable platform extension, supported by bounded retrieval evidence, rather than a new retrieval algorithm or a claim that all success criteria were achieved.

The report first establishes the application needs and synthesises relevant research and platform alternatives into five design questions. It then explains the architecture, interaction and operational choices, traces delivery and member contributions, and analyses the available results. The final reflection identifies lessons from access-aware delegation, provider compatibility, reusable interfaces and developer onboarding, with validation priorities for continued development.
