#import "../style.typ": tab
= Project background and problem statement

== Organisational context and the starting point

NTG-agent-vnext is the QUOTA team's capstone contribution to NashTech's NTG Agent platform. Its central concern is how an organisation can configure assistants over its documents while controlling which users may invoke each assistant and its specialists. The starting repository already provided a C\# conversational application with agent configuration, model-provider connections and supporting services. The team extended this foundation through agent-scoped knowledge, caller-aware delegation and reusable interactive workflows. The report attributes these extensions through the reviewed GitHub history rather than claiming authorship of the entire platform. @implementation @githubhistory

The completion plan describes four initial ambitions: a richer document-search pipeline, layered memory, planner-and-worker coordination, and an interface that could compose structured responses. It also records a subsequent concentration on LightRAG, assistants-as-tools, skills and role-based access. @completion These changes show that the project problem was broader than connecting a chat box to a model. It concerned how several assistants could share an application environment while retaining distinct responsibilities, knowledge and permissions.

For a document-grounded assistant, organisational information must be made available at the point of answering. RAG addresses part of this need by retrieving external evidence to condition generation. @rag However, retrieving a relevant document is only one stage of the user journey. The application must also determine which assistant a user can invoke, which documents that assistant searches, whether the selected provider configuration works, and how a multi-step task is presented to the user. NTG-agent-vnext addresses this combination of administration and runtime behaviour.

== Why the application is needed

Consider an illustrative internal helpdesk derived from the project's requirements. An administrator configures a user-facing assistant, assigns its documents and access roles, and binds specialist assistants for separate areas of knowledge. After signing in, a user selects an available assistant and asks a question. The assistant may retrieve from its own collection or consult an eligible specialist. In the latter case, the specialist searches its own knowledge base and returns an answer that the user-facing assistant can incorporate into the response. This is a requirement-derived workflow, not a recorded sponsor interaction.

The critical condition is the caller's permission. Binding a specialist to the helpdesk should not make that specialist available to every helpdesk user. The runtime must check access before exposing the specialist and again before invoking it. If access is denied, the general assistant must not become an indirect route around the restriction. Conversely, an authorised specialist is expected to return relevant information: separate knowledge ownership does not mean that all information exchange between assistants is prohibited.

Making this workflow configurable also requires usable model settings. An administrator adds a model endpoint, fetches its models or deployments, and enables a model for an agent. A catalogue entry does not establish that every optional request parameter will be accepted. The administrator therefore needs feedback before enabling thinking mode. GitHub history makes this need concrete: provider routing was revised in PR 281, while PR 287 replaced a curated thinking-capability list with a live request probe. @githubhistory

Some requests also require structured interaction: a user supplies several fields, compares options and reviews a result. Skill templates and streamed UI events give the application an explicit representation of these inputs and steps. They extend the same configured-assistant workflow beyond a text answer. The included travel-planning and ticket-booking packages illustrate the interaction pattern with synthetic demonstration data; they are not evidence of real reservations or completed business transactions.

== Stakeholders, needs and expected value

The requirements imply four operational perspectives. End users need a coherent route from a question to relevant assistance. Administrators need control over what is published and available. Skill authors need a manageable way to express task instructions and interaction structure. Developers and maintainers need to reproduce the environment and diagnose integration failures. @table-stakeholders connects these needs to concrete application responsibilities.

#tab((0.85fr, 1.45fr, 1.6fr, 1.2fr), ([Stakeholder], [Need or difficulty], [Application responsibility], [Expected value]), (
  [End user], [Find help from appropriate documents or specialist capabilities without manually navigating every backend.], [Published-agent discovery, authenticated conversation, authorised delegation and readable tool results.], [A continuous interaction with explicit permission boundaries.],
  [Agent administrator], [Configure knowledge, roles, tools, providers and available models consistently.], [Agent-scoped knowledge services, access bindings, provider catalogues and capability probes.], [Configuration decisions that are visible and actionable.],
  [Skill author / administrator], [Add repeatable task guidance and structured input without a bespoke frontend component for each variation.], [SKILL.md packages, validated surface templates and per-agent bindings.], [Task-specific extension through reviewed configuration.],
  [Developer / maintainer], [Prepare local services, handle container routing and diagnose failures across components.], [Setup scripts, provisioning status, gateway routing and implementation documentation.], [A more reproducible development and handover process.],
), [Stakeholder needs derived from project requirements and implemented workflows. Expected value is a design rationale, not a measured usability outcome.]) <table-stakeholders>

These needs are connected. Publishing an agent before its knowledge service is ready creates a user-facing failure even if the chat interface itself is available. Providing a model selector without usable endpoint configuration moves an integration problem into the conversation. Allowing a skill to render a form whose fields cannot accept input undermines the workflow even when the model produces plausible text. The application therefore requires consistency across its administrative decisions, backend services and client presentation.

The reviewed history contains concrete responses to these difficulties. LightRAG provisioning became a background process with status tracking; gateway routing replaced a host-port ledger; skill validation checked template structure and data bindings; and setup automation prepared dependencies and default-agent configuration. @githubhistory These changes substantiate the practical engineering need for the application. They do not require an invented claim about how many staff hours were lost or how many employees adopted the system.

The distinction between platform value and measured benefit remains important. The project supplies mechanisms that can reduce repeated configuration and interface work, but no controlled productivity study or representative user evaluation has been supplied. The appropriate claim is that the platform implements the capabilities needed to support those workflows. The extent of improvement in staff efficiency, task success or administrator workload is a subsequent empirical question.

== Problem statement and project objectives

The project addresses the following problem: *how can an existing .NET application let administrators configure document-grounded assistants whose specialist delegation remains subject to the caller's permissions?* Provider configuration and reusable interfaces support this central workflow: a selected model must accept the intended request, and a task instruction must reach a client capable of presenting its interaction. The difficulty lies in making these administrative choices effective throughout the user's request.

Five objectives make the problem assessable. First, each knowledge-enabled agent should have a defined retrieval context and a document lifecycle that distinguishes upload from indexing readiness. Second, the runtime should expose and invoke specialist agents according to the caller's permissions. Third, administrators should manage available models and test optional thinking behaviour through the runtime request path. Fourth, skills and structured UI events should support reusable task flows. Fifth, the project should leave a reproducible setup process and evidence with which these capabilities can be evaluated.

These objectives also define boundaries. The project does not develop a new foundation model or retrieval algorithm. It adopts existing frameworks and protocols, then contributes the integration, configuration and lifecycle logic needed in this application. The retained design does not implement the completion plan's proposed many-to-many shared knowledge spaces, and removal of the earlier long-term memory backend is a documented scope decision. Likewise, demonstration skills are not integrations with live booking or enterprise transaction systems. @completion @githubhistory

== Constraints and significance

The work operates within an existing .NET application, a capstone delivery schedule and externally provided model services. Per-agent knowledge services introduce container and storage coordination, while the conversational frontend adds another process and protocol boundary. NashTech's infrastructure support and the university's Claude API allocation helped the team develop and test within these constraints. The reported setup friction also made local reproducibility a practical requirement rather than an incidental documentation task.

The project's significance is its treatment of the assistant as an administered application. The administrator defines the available capabilities; the runtime applies those choices during delegation and retrieval; and the client renders supported interactions. This is useful beyond a single demonstration because future assistants can reuse the same configuration and integration mechanisms while differing in their documents, permitted users and task guidance. The claim is a reusable engineering approach, not established superiority over every alternative platform.

The completion plan provides measurable targets for retrieval, answer quality, ingestion, response latency, availability and cost. @completion GitHub integration records establish when selected capabilities entered main, while the supplied retrieval trials establish a narrower set of observed outcomes. The report uses both forms of evidence: implementation and contribution records explain what was delivered; experimental results examine how the tested retrieval configuration behaved. Section 3 derives the design questions from prior work, Section 4 explains the solution and its development, and Section 5 assesses the available results against the retained objectives.
