== Provider configuration and capability checks

Provider configuration separates an endpoint and its available models from the settings of an individual agent. An administrator manages the provider, fetches the catalogue or deployments exposed by it, enables suitable models, and selects one explicitly for each agent. PR 287 introduced the global provider/model management workflow, building on the earlier discovery and routing changes. This separation avoids treating every agent as an independent copy of the provider configuration while retaining agent-specific model choice. @githubhistory

The workflow also separates availability from compatibility. A catalogue response indicates that a model or deployment is advertised through the queried endpoint. Thinking support is tested separately by sending a small request through the same thinking-client construction path used during chat. The implementation uses a 30-second timeout and returns a structured result with an error when the request fails. A successful probe establishes acceptance of the tested request configuration at that time; it does not measure reasoning quality or establish that every optional setting is supported. @implementation

The final design emerged through two distinct revisions. PR 281 corrected provider-specific endpoint and reasoning routing and extracted client-construction responsibilities. PR 287 subsequently moved thinking-mode gating away from a curated capability list. Its 26 August commit introduced the live probe, so the final runtime contract is more precise than the PR's earlier summary. This is why the report follows the commit and final code when describing the feature.

Errors are part of the administrative workflow. An invalid endpoint, a discovery failure and a rejected thinking request should lead to actionable configuration feedback rather than an unexplained failure during the user's first conversation. At the same time, a timeout cannot reliably distinguish an unsupported option from an unavailable service. The result therefore includes the error context, and runtime calls still require their own failure handling.

There is also a consistency requirement between probing and use. A probe implemented through a separate request builder could accept a payload that the agent never sends. Reusing the thinking-client construction path reduces that mismatch. The probe is still a small compatibility request with its own input and options; the report does not describe it as a complete replay of every later conversation request.

The implemented workflow answers DQ3 by making provider/model decisions explicit and testable. Its next acceptance checks should cover successful discovery, unavailable catalogues, permission failures, accepted and rejected thinking requests, and saved agent settings. Output quality remains a separate evaluation dimension. This distinction allows administrators to select a usable configuration without representing compatibility as a ranking of model intelligence.

== Skills and interactive responses

A skill is stored as a package of task instructions and supporting assets that an administrator imports and binds to an agent. PR 286 added the storage, administrative API, interface and runtime path for these packages. At the start of a run, the agent receives a compact catalogue of bound skill names and descriptions. The #raw("load_skill") tool supplies the detailed instructions when a skill is needed, while #raw("render_skill_surface") renders an authored template with task-specific values. @githubhistory @implementation

This progressive loading has a specific purpose: every bound skill need not contribute its entire instruction body to every request. The runtime guidance also tells the model to reload a skill when continuing its task on a later turn, because the loaded body is not retained as ordinary conversation history. The project therefore treats skill activation and conversation persistence as separate mechanisms, rather than assuming that a previously loaded instruction remains available indefinitely.

The presentation path retains two forms of declarative output. The general #raw("render_a2ui") tool can construct a surface against the supported catalogue. The skill path uses a template authored in advance and changes its data at runtime. For a repeated multi-step flow, the latter keeps the input fields and layout stable while allowing the model to supply the relevant content. The travel-planning and ticket-booking packages demonstrate this pattern using synthetic data.

The practical change is where task-specific interface work occurs. The earlier per-tool approach required a corresponding frontend component; supported declarative surfaces can instead reuse the client renderer and component catalogue. Skill authors still define templates, input bindings and instructions. The contribution is therefore configurable interaction without a bespoke frontend component for each supported task variation, rather than an interface that required no human authoring. This complements the administrator's ability to configure knowledge and delegation within the same platform.

Validation occurs at import as well as during rendering. The package importer checks archive entries and rejects problematic paths and duplicates. The surface validator checks component structure, references and data bindings. In particular, input paths need seeded values: an apparently valid control can otherwise render without a usable update target. This is a concrete example of an interface failure that cannot be detected by judging the model's text alone.

PR 286 also addresses continuity and client differences. Stable surface identifiers allow an updated skill surface to remain in the existing card, and skill surfaces have a replay path after a page reload. Generative output is gated by what the client can render, avoiding the display of protocol payloads as ordinary assistant text. These changes connect DQ4 to an explicit interaction contract: a surface must remain addressable, its fields must function, and unsupported clients must receive appropriate handling.

The package format is intentionally constrained. Executable scripts are outside the supported skill path, and structural checks do not establish that every instruction is trustworthy. The remaining questions concern content and use: whether a skill chooses the right next step, preserves user selections and produces a correct result. Tests of the importer and surface schema provide one layer of evidence; live multi-turn tasks and human assessment provide the complementary layer. No general prompt-injection resistance or real booking functionality is claimed.

== Operability and development support

The platform's resource model makes lifecycle management part of the user experience. A knowledge-enabled agent may need a container to be provisioned, an indexing job to finish or a service to become ready before a query can succeed. The GitHub record distinguishes these concerns: PR 265 includes per-agent containers, document-status handling and idle shutdown, while PR 282 adds provisioning-state work, VM migration and gateway routing. @githubhistory

The gateway replaces the earlier host-port ledger with agent-addressed routing. This gives the application a consistent route for selecting the intended LightRAG service, while container startup and readiness remain separate responsibilities. Shared PostgreSQL infrastructure stores agent-scoped knowledge through distinct workspace configuration. The resulting topology supports per-agent ownership but still depends on shared services, correct routing and working credentials.

Local installation was developed as an end-to-end workflow. PR 285 adds a bootstrap and setup script that checks prerequisites, obtains the required Azure endpoint and key, generates other local secrets, writes configuration, starts the local knowledge stack and launches the application host. Ubuntu/Debian and macOS have different prerequisite paths; macOS still requires an available Docker environment. Existing configuration is preserved where the script supports reuse. The design reduces the number of manual transitions between setup stages, although no timed onboarding comparison was supplied.

Default-agent provisioning connects setup to the model configuration. The seeder fills an unconfigured default agent from the available LightRAG model settings, enabling a first conversation without a separate provider-entry step. The final implementation checks whether a provider key is already present before filling it, so a configured provider is not indiscriminately overwritten. A September integration change adapted this logic to the provider entity introduced by PR 287. @implementation @githubhistory

The workflow history also records supporting maintenance. PRs 278 and 280 add secret-scanning configuration and repair the scanner runtime used by CI. PR 288 updates dependencies and integration code. These changes support continued development, but a configured workflow is not evidence that every merge passed its quality gate. Author-reported checks in PRs are distinguished from independently inspected run records.

Operational evaluation remains a separate deliverable. Telemetry and development health endpoints provide implementation hooks; the retrieval trial supplies sampled health observations. Neither establishes a complete demonstration-window availability record, a backup/restore result or a recovery-time distribution. DQ5 therefore calls for a repeatable fresh-environment setup, recovery exercises and retained runtime measurements. The current contribution is the integrated setup and lifecycle tooling with traceable development history, ready to support those checks.
