// Generated by build-delivery-timeline.py. Edit the evidence JSON or feature mapping instead.
#let pr-rows = (
  [#link("https://github.com/nashtech-garage/ntg-agent/pull/261")[PR 261]], [GarrettTran], [06-01], [06-19], [#raw("5ec09cd")],
  [#link("https://github.com/nashtech-garage/ntg-agent/pull/264")[PR 264]], [TienNgen], [06-12], [07-07], [#raw("ec4b312")],
  [#link("https://github.com/nashtech-garage/ntg-agent/pull/265")[PR 265]], [AnVuGia], [06-29], [07-17], [#raw("21c4684")],
  [#link("https://github.com/nashtech-garage/ntg-agent/pull/277")[PR 277]], [AnVuGia], [07-17], [07-23], [#raw("0443991")],
  [#link("https://github.com/nashtech-garage/ntg-agent/pull/278")[PR 278]], [AnVuGia], [07-18], [07-22], [#raw("21030d7")],
  [#link("https://github.com/nashtech-garage/ntg-agent/pull/280")[PR 280]], [AnVuGia], [07-22], [07-22], [#raw("1792969")],
  [#link("https://github.com/nashtech-garage/ntg-agent/pull/281")[PR 281]], [AnVuGia], [07-22], [07-23], [#raw("b8b2304")],
  [#link("https://github.com/nashtech-garage/ntg-agent/pull/282")[PR 282]], [Annie-Chau], [08-02], [08-20], [#raw("4823553")],
  [#link("https://github.com/nashtech-garage/ntg-agent/pull/285")[PR 285]], [AnVuGia], [08-19], [09-13], [#raw("7789ed0")],
  [#link("https://github.com/nashtech-garage/ntg-agent/pull/286")[PR 286]], [TienNgen], [08-20], [08-25], [#raw("954f497")],
  [#link("https://github.com/nashtech-garage/ntg-agent/pull/287")[PR 287]], [GarrettTran], [08-20], [09-03], [#raw("9847237")],
  [#link("https://github.com/nashtech-garage/ntg-agent/pull/288")[PR 288]], [sieunhantanbao], [08-30], [09-03], [#raw("33733bb")],
)
